logLevel = "DEBUG"

[web]
address = ":50801"

[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix://var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Required
#
domain = "jad"

# Enable watch docker changes
#
# Optional
#
watch = true
